sudo: false

language: python

matrix:
  include:
  - python: 3.6
    env: TOXENV=py
  - python: 3.5
    env: TOXENV=py

install:
- pip install tox

script:
- tox

before_cache:
- rm -rf $HOME/.cache/pip/log

cache:
  directories:
  - $HOME/.cache/pip

deploy:
  matrix:
  - provider: pypi
    user: jbasko
    password:
      secure: nAqH31CWFEGSwTIqFma5W2xYgExsdNhV2pXxcEjQvkxLQiMcojgA+bBEW9rdtlFrD92Q0g62LXu2h60UsJYeb2+czWiFqYROfAEbRwLbUrQWSVBY7hxlrH3eE/mL7iYAJscsDxVbKE23nLDeLczsfhRUK5/UKjo2KNBIgc5WAoHA94+M+bCOzZlcrrjsHj8Tmg5oy/WkueejAFvw7rs9PJi2+qCBbbtZRhNc1dNY29zfTi+PhMX5WB80KgbtwoGk6ldebEmVOG3FRpelvN30UpHfjpSFZfikQpCkBSwwmLY6RHrYcbZjjudeI/yF3ywrJw4EMNBfQh1PL6VyHU5c+D+zJeyFjH7hU3494dvKOd1q6RCvETpLQeN4HP3YOieSe6uxYMybZhuL91xPrS4QGloSpLB2fZOImSg+1rKP1d+6sY0jDN4ioydvLZwLWT/l9OOVdNbbvaDBNyz3bEnYci8BWBnHhAK3TbKH9/wZF6GOQ9/DIC53aWvjjOMxzNjhcxvWGNnNHEEbWt+D0U+EnQdIherpfjHo2SW0DPMMGbGB1q+t00FHhCwUiOFLJ3hRpg/AQ5m8m9gMJwUqekPmJk3k3APFcQBPhKHL9LMd5Y5HUrnTuliH+KhbeA1YLgbVdVUzZYwZmihGrnQylpVsnfNqDZ9Amu+uwaAfkumr6O0=
    on:
      tags: true
      branch: master
      python: 3.6
